# Generated by Django 3.2.4 on 2021-06-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название акции')),
                ('discount_percentage', models.IntegerField(verbose_name='Процент скидки')),
                ('start_promotions_date', models.DateField(verbose_name='Начало акции')),
                ('end_promotions_date', models.DateField(verbose_name='Конец акции')),
            ],
        ),
    ]
