# Generated by Django 3.2.4 on 2021-06-15 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIpromotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotionsmodel',
            options={'ordering': ['-start_promotions_date'], 'permissions': (('can_publish', 'Может публиковать'),), 'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
    ]
