# Generated by Django 2.2 on 2021-05-04 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=1000, verbose_name='Заголовок')),
                ('description', models.TextField(db_index=True, default='', max_length=1000, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('when_to_stop_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='дата окончания публикации')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('view_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'db_table': 'Advertisements',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adcategories', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='AdvertisementStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Cтатус')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('number_phones', models.IntegerField(verbose_name='Телефон')),
                ('advertisement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='advertisements_app.Advertisement', verbose_name='Объявления')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='categories',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='advertisements_app.AdvertisementCategories', verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='advertisements_app.AdvertisementStatus', verbose_name='Статус'),
        ),
    ]
