# Generated by Django 2.2 on 2021-05-03 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0002_auto_20210503_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adcategories', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('number_phones', models.IntegerField(verbose_name='Телефон')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='when_to_stop_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='advertisementstatus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Cтатус'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='categories',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AdvertisementCategories', to='advertisements_app.AdvertisementCategories', verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserAdvertisement', to='advertisements_app.User', verbose_name='Пользователь'),
        ),
    ]
