# Generated by Django 3.2.4 on 2021-06-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0003_alter_bookmodel_isbn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmodel',
            options={'verbose_name': 'Книна', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='isbn',
            field=models.IntegerField(default=692987075),
        ),
    ]
