# Generated by Django 3.2.4 on 2021-06-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0004_auto_20210612_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmodel',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='count_pages',
            field=models.IntegerField(default=1, verbose_name='Количество листов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='isbn',
            field=models.IntegerField(default=753369382),
        ),
    ]
