# Generated by Django 3.2.4 on 2021-06-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0012_alter_bookmodel_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='isbn',
            field=models.IntegerField(default=943291103),
        ),
    ]
