# Generated by Django 3.2.4 on 2021-06-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='group_name',
            field=models.ManyToManyField(blank=True, related_name='test', related_query_name='name1', to='app_goods.ItemGroupModel', verbose_name='Группа товара'),
        ),
    ]
