# Generated by Django 2.2 on 2021-05-30 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('product', models.CharField(max_length=30, verbose_name='Товар')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('article', models.AutoField(primary_key=True, serialize=False, verbose_name='Артикул')),
            ],
        ),
        migrations.CreateModel(
            name='ShopsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_shop', models.CharField(max_length=30, verbose_name='Название магазина')),
                ('telephone', models.CharField(max_length=30, verbose_name='Телефон магазина')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена покупки')),
                ('purchase_date', models.DateField(auto_now_add=True, verbose_name='Дата покупки')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='app_shops.ProductsModel', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Имя покупателя')),
            ],
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='app_shops.ShopsModel', verbose_name='Магазин'),
        ),
    ]
