# Generated by Django 2.2 on 2021-05-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistorymodel',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки'),
        ),
    ]
