# Generated by Django 3.2.4 on 2021-06-09 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0002_auto_20210531_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=500, verbose_name='Предложение')),
                ('validity_period', models.DateField(default=datetime.date(2021, 6, 16), null=True)),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.CreateModel(
            name='PromotionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.CharField(max_length=100, verbose_name='Акция')),
                ('validity_period', models.DateField(default=datetime.date(2021, 6, 16), null=True)),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
