# Generated by Django 3.2.4 on 2021-06-17 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_blogs', '0002_alter_post_moderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification', models.CharField(blank=True, choices=[('newbie', 'Новичок'), ('Advanced', 'Продвинутый'), ('Expert', 'Эксперт')], default='newbie', max_length=10, verbose_name='Флаг верификации')),
                ('points_status', models.IntegerField(default=500, verbose_name='баллы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Аккаунт(ы)',
            },
        ),
    ]
