# Generated by Django 2.2 on 2021-05-14 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='Город')),
                ('verification', models.CharField(blank=True, choices=[('u', 'Обычный пользователь'),
                                                                       ('v', 'Верифицированный пользователь'),
                                                                       ('m', 'Модератор')], default='u', max_length=1,
                                                  verbose_name='Флаг верификации')),
                ('count_published_news',
                 models.IntegerField(blank=True, default=0, verbose_name='Количество опубликованных новостей')),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аккаунт(ы)',
                'verbose_name_plural': 'Профиль',
            },
        ),
    ]
