# Generated by Django 2.2 on 2021-05-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='app_news.Tag', verbose_name='Теги'),
        ),
    ]
